### ISSUE TITLE
consider using foreman upstream image

### ISSUE THREAD

**Issue by ohadlevy** [ReadyTalk/foreman-docker#2]
Hi,

during the last few months, foreman itself maintain an image (see https://community.theforeman.org/t/dockerfile-is-now-included-in-foreman-core/13987), I was wondering if you still use this environment and would consider to join the effort to make it available to the larger community.

secondly, I maintain a https://github.com/ohadlevy/foreman-kube repo, and was wondering if it make sense to try and unify, thanks for your efforts so far!
Ohad

**Comment by lwahlmeier** [comment]
Thanks for the comment, we actually are not using forman for really anything anymore so this project is pretty much just dead.  I will mark it as such.
